name: Display GitHub Actions vars context Environment Variables

on:
  # push:
  #   branches: [ develop ]
  # pull_request:
  #   branches: [ develop ]
  # 
          # for var in ${{ vars }}; do
          #   echo "$var"
          # for i in ${ALLMYVARS}
  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:

env:
  NEXT_PUBLIC_VARIABLE_ONE: ${{vars.NEXT_PUBLIC_VARIABLE_ONE}}
  NEXT_PUBLIC_VARIABLE_TWO: ${{vars.NEXT_PUBLIC_VARIABLE_TWO}}
  ALLMYVARS: ${{ toJSON(vars) }}
jobs:
  display_variables:
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
      - name: Display GitHub Actions Environment Variables
        id: define-variables
        run: |
          echo ${{vars.APP_NAME}}
          echo ${{env.NEXT_PUBLIC_VARIABLE_ONE}}
          echo "${ALLMYVARS}"
          variables=""
          for key in $(echo "$ALLMYVARS" | jq -r 'keys[]' | grep '^NEXT_PUBLIC')
          do
            value=$(echo "$ALLMYVARS" | jq -r --arg key "$key" '.[$key]')
            echo "Key: $key , Value: $value"
            variables+="--build-arg $key=$value "
          done
          echo "define_var=$variables" >> "$GITHUB_OUTPUT"
      - name: Use Displayed Variables
        run: |
          echo "${{ steps.define-variables.outputs.define_var }}"
          displayed_variables="${{ steps.define-variables.outputs.define_var }}"
          echo "$displayed_variables"


    
         
