name: Display GitHub Actions vars context Environment Variables

on:
  push:
    branches:
      - main

jobs:
  display_variables:
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
      - name: Display GitHub Actions Environment Variables
        run: |
          for var in ${{ toJson(vars) }}; do
            echo "$var"
          done
