name: Display GitHub Actions vars context Environment Variables

on:
  # push:
  #   branches: [ develop ]
  # pull_request:
  #   branches: [ develop ]
  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:

jobs:
  display_variables:
    runs-on: ubuntu-latest
    environment: sandbox

    steps:
      - name: Display GitHub Actions Environment Variables
        run: |
          for var in ${{ toJson(vars) }}; do
            echo "$var"
          done
